### ISSUE TITLE
 FPC trunk compilation fails for Win32

### ISSUE THREAD

**Issue by zoltanleo** [blikblum/VirtualTreeView-Lazarus#11]
# What is the VirtualTreeView version / branch?
5.5.3.1

# What is the Lazarus and Freepascal version?
fpc r.41348, laz r60440

Can't install subj with error message
**VirtualTrees.pas(769,19) Error: No matching implementation for interface method "SetData(const tagFORMATETC;var TagSTGMEDIUM;LongBool):LongInt; StdCall;" found** 

because the changes in FPC ActiveX headers is causing compilation issue.

Pls, fix it.

**Comment by blikblum** [comment]
Fixed in https://github.com/blikblum/VirtualTreeView-Lazarus/commit/ed5877e899cc56d8190a9b0665c7e2fffc1bfeab

**Comment by zoltanleo** [comment]
It's OK. Thunk U
